import {
  ambassador_link,
  bridge_link,
  bsctest_faucet_link,
  network_link,
  developer_link,
  discord_link,
  docs_link,
  evm_explorer_link,
  linktree_link,
  medium_link,
  rinkeby_faucet_link,
  telegram_link,
  tele_faucet_link,
  tendermint_explorer_link,
  twitter_link,
  validators_link,
  wallet_doc_link,
  wallet_download_link,
  whitepaper_link,
  XIBC_link,
  swap_link,
} from 'constants/url'
import { genSensorCallback } from './skynet'

export const presetSensors = {
  header: {
    ambassador: genSensorCallback('header', 'ambassador', ambassador_link),
    twitter: genSensorCallback('header', 'twitter', twitter_link),
    telegram: genSensorCallback('header', 'telegram', telegram_link),
    discord: genSensorCallback('header', 'discord', discord_link),
    medium: genSensorCallback('header', 'medium', medium_link),
    linktree: genSensorCallback('header', 'linktree', linktree_link),
    whitepaper: genSensorCallback('header', 'whitepaper', whitepaper_link),
    network: genSensorCallback('header', 'docChain', network_link),
    xibc: genSensorCallback('header', 'xibc', XIBC_link),
    developer: genSensorCallback('header', 'developer', developer_link),
    validator: genSensorCallback('header', 'validator', validators_link),
    walletDoc: genSensorCallback('header', 'walletDoc', wallet_doc_link),
    teleFaucet: genSensorCallback('header', 'teleFaucet', tele_faucet_link),
    bscFaucet: genSensorCallback('header', 'bscFaucet', bsctest_faucet_link),
    rinkebyFaucet: genSensorCallback('header', 'rinkebyFaucet', rinkeby_faucet_link),
    evmExplorer: genSensorCallback('header', 'evmExplorer', evm_explorer_link),
    tendermintExplorer: genSensorCallback('header', 'tendermintExplorer', tendermint_explorer_link),
  },
  body: {
    twitter: genSensorCallback('body', 'twitter'),
    telegram: genSensorCallback('body', 'telegram'),
    discord: genSensorCallback('body', 'discord'),
    medium: genSensorCallback('body', 'medium'),
    linktree: genSensorCallback('body', 'linktree'),
    launchBridge: genSensorCallback('body', 'launchBridge', bridge_link),
    downloadWallet: genSensorCallback('body', 'downloadWallet', wallet_download_link),
    goToSwap: genSensorCallback('body', 'goToSwap', swap_link),
    doc: genSensorCallback('body', 'doc', docs_link),
    whitepaper: genSensorCallback('body', 'whitepaper', whitepaper_link),
  },
  footer: { ambassador: genSensorCallback('footer', 'ambassador'), doc: genSensorCallback('footer', 'doc'), github: genSensorCallback('footer', 'github'), discord: genSensorCallback('footer', 'discord') },
}
